/// <reference path="./globals.d.ts" />
declare const HOUR: 3600000;
declare const SLOT_FEET: EquipmentSlot;
declare const SLOT_HEAD: EquipmentSlot;
declare const global: {
    jeiRuntime: Unknown.JeiRuntime;
    isExpertMode: boolean;
    onReload: () => {/**@file {kubejs\startup_scripts\reload.js} */};
    packmode: string;
    isNormalMode: boolean;
};
declare const TOOL_TYPE_SHOVEL: ToolType;
declare const SLOT_LEGS: EquipmentSlot;
declare const TOOL_TYPE_AXE: ToolType;
declare const AIR_ITEM: Internal.AirItem;
declare const RARITY_EPIC: Rarity;
declare const Painter: Internal.Painter;
declare const client: Internal.ClientWrapper;
declare const MINUTE: 60000;
declare const SLOT_OFFHAND: EquipmentSlot;
declare const Client: Internal.ClientWrapper;
declare const events: Internal.ScriptEventsWrapper;
declare const TOOL_TYPE_HOE: ToolType;
declare const OFF_HAND: Hand;
declare const settings: Internal.ServerSettings;
declare const console: Internal.ConsoleJS;
declare const RARITY_RARE: Rarity;
declare const TOOL_TYPE_PICKAXE: ToolType;
declare const MAIN_HAND: Hand;
declare const AIR_BLOCK: Internal.AirBlock;
declare const RARITY_UNCOMMON: Rarity;
declare const SLOT_CHEST: EquipmentSlot;
declare const SECOND: 1000;
declare const RARITY_COMMON: Rarity;
declare const SLOT_MAINHAND: EquipmentSlot;
