

captureEvent("command.registry", (event) => { console.info("command.registry") })
captureEvent("command.run", (event) => { console.info("command.run") })
captureEvent("server.load", (event) => { console.info("server.load") })
captureEvent("server.unload", (event) => { console.info("server.unload") })
// captureEvent("server.tick", (event)=>{console.info("server.tick")})
captureEvent("server.datapack.first", (event) => { console.info("server.datapack.first") })
captureEvent("server.datapack.last", (event) => { console.info("server.datapack.last") })
captureEvent("recipes", (event) => { console.info("recipes") })
captureEvent("world.load", (event) => { console.info("world.load") })
captureEvent("world.unload", (event) => { console.info("world.unload") })
// captureEvent("world.tick", (event)=>{console.info("world.tick")})
captureEvent("world.explosion.pre", (event) => { console.info("world.explosion.pre") })
captureEvent("world.explosion.post", (event) => { console.info("world.explosion.post") })
captureEvent("player.logged_in", (event) => { console.info("player.logged_in") })
captureEvent("player.logged_out", (event) => { console.info("player.logged_out") })
// captureEvent("player.tick", (event)=>{console.info("player.tick")})
// captureEvent("player.data_from_client.<信道>", (event)=>{console.info("player.data_from_client.<信道>")})
captureEvent("player.chat", (event) => { console.info("player.chat") })
captureEvent("player.advancement", (event) => { console.info("player.advancement") })
captureEvent("player.inventory.opened", (event) => { console.info("player.inventory.opened") })
captureEvent("player.inventory.closed", (event) => { console.info("player.inventory.closed") })
captureEvent("player.inventory.changed", (event) => { console.info("player.inventory.changed") })
captureEvent("player.chest.opened", (event) => { console.info("player.chest.opened") })
captureEvent("player.chest.closed", (event) => { console.info("player.chest.closed") })
captureEvent("entity.death", (event) => { console.info("entity.death") })
captureEvent("entity.attack", (event) => { console.info("entity.attack") })
captureEvent("entity.drops", (event) => { console.info("entity.drops") })
// captureEvent("entity.check_spawn", (event)=>{console.info("entity.check_spawn")})
// captureEvent("entity.spawned", (event)=>{console.info("entity.spawned")})
captureEvent("block.missing_mappings", (event) => { console.info("block.missing_mappings") })
captureEvent("block.tags", (event) => { console.info("block.tags") })
captureEvent("block.right_click", (event) => { console.info("block.right_click") })
captureEvent("block.left_click", (event) => { console.info("block.left_click") })
captureEvent("block.place", (event) => { console.info("block.place") })
captureEvent("block.break", (event) => { console.info("block.break") })
captureEvent("block.drops", (event) => { console.info("block.drops") })
captureEvent("item.food_eaten", (event) => { console.info("item.food_eaten") })
captureEvent("item.missing_mappings", (event) => { console.info("item.missing_mappings") })
captureEvent("item.tags", (event) => { console.info("item.tags") })
captureEvent("item.right_click", (event) => { console.info("item.right_click") })
captureEvent("item.entity_interact", (event) => { console.info("item.entity_interact") })
captureEvent("item.pickup", (event) => { console.info("item.pickup") })
captureEvent("item.toss", (event) => { console.info("item.toss") })
captureEvent("item.crafted", (event) => { console.info("item.crafted") })
captureEvent("item.smelted", (event) => { console.info("item.smelted") })
captureEvent("fluid.tags", (event) => { console.info("fluid.tags") })
captureEvent("entity_type.tags", (event) => { console.info("entity_type.tags") })

// onEvent('item.right_click', e => {
//     e.player.tell(Ingredient.of('@mctb').stacks.toArray())
// })